version: '2.3'

services:

  inpainting:
    image: inpainting
    container_name: inpainting
    working_dir: /inpainting
    build:
      context: ../
      dockerfile: docker/Dockerfile
 
    volumes:
      - ../:/inpainting
    runtime: nvidia
    command: tail /dev/null -f
